-- liquibase formatted SQL

-- changeset igor:1 dbms:h2
CREATE TABLE ROLE (
  ROLE_ID int(11) NOT NULL AUTO_INCREMENT,
  ROLE varchar(255) DEFAULT NULL,
  PRIMARY KEY (ROLE_ID)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

CREATE TABLE USER (
  USER_ID int(11) NOT NULL AUTO_INCREMENT,
  ACTIVE int(11) DEFAULT NULL,
  USERNAME varchar(255) NOT NULL,
  LAST_NAME varchar(255) NOT NULL,
  NAME varchar(255) NOT NULL,
  PASSWORD varchar(255) NOT NULL,
  PRIMARY KEY (USER_ID)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE USER_ROLE (
  USER_ID int(11) NOT NULL,
  ROLE_ID int(11) NOT NULL,
  PRIMARY KEY (USER_ID, ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE LOGIN_HISTORY (
  ID int(11) NOT NULL AUTO_INCREMENT,
  USER_ID int(11) NOT NULL,
  DATE timestamp NOT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ROLLBACK DROP TABLE ROLE
-- ROLLBACK DROP TABLE USER
-- ROLLBACK DROP TABLE USER_ROLE
-- ROLLBACK DROP TABLE LOGIN_HISTORY

-- changeset igor:2 dbms:h2
INSERT INTO ROLE VALUES (1,'USER');
-- ROLLBACK DELETE FROM ROLE WHERE ROLE_ID = 1

-- changeset igor:3 dbms:h2
INSERT INTO USER_ROLE VALUES (1, 1);
-- ROLLBACK DELETE FROM USER_ROLE WHERE USER_ID = 1 AND ROLE_ID = 1

-- changeset igor:4 dbms:h2
INSERT INTO USER (ACTIVE, USERNAME, LAST_NAME, NAME, PASSWORD) VALUES (true, 'igor', 'Leal', 'Igor', 'password');
-- ROLLBACK DELETE FROM USER WHERE USER_ID = 1