-- liquibase formatted SQL

-- changeset igor:1 dbms:h2
CREATE TABLE USER (
  USER_ID int(11) NOT NULL AUTO_INCREMENT,
  ACTIVE int(11) DEFAULT NULL,
  USERNAME varchar(255) NOT NULL,
  LAST_NAME varchar(255) NOT NULL,
  NAME varchar(255) NOT NULL,
  PASSWORD varchar(255) NOT NULL,
  PRIMARY KEY (USER_ID)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE LOGIN_HISTORY (
  ID int(11) NOT NULL AUTO_INCREMENT,
  USER_ID int(11) NOT NULL,
  DATE timestamp NOT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ROLLBACK DROP TABLE USER
-- ROLLBACK DROP TABLE LOGIN_HISTORY


-- changeset igor:2 dbms:h2
INSERT INTO USER (ACTIVE, USERNAME, LAST_NAME, NAME, PASSWORD) VALUES (true, 'igor', 'Leal', 'Igor', '78b6854e22ab09d4ae3dac29b92052963103b33e');
-- ROLLBACK DELETE FROM USER WHERE USER_ID = 1